[package]
name = "plygui-markup-test"
version = "0.1.0"
authors = ["snuk182 <snuk188@gmail.com>"]

[[bin]]
name = "markuptest"
path = "src/main.rs"

[dependencies]
plygui-markup = {version = "0.0.1", path = "../plygui-markup", features = ["win32"]}